using System;

namespace Wizzi.Entities
{
    public partial class Parametros
    {
        public string EmpresasParametro { get; set; }
        public string SucursalesParametro { get; set; }
        public double PorcentajePrecioParametro { get; set; }
        public string MetodoCostoParametro { get; set; }
        public double? IvaParametro { get; set; }
        public string BodegaCompraParametro { get; set; }
        public string BodegaVentaParametro { get; set; }
        public string BodegaProduccionParametro { get; set; }
        public sbyte VerPrecioOrdenPedidoParametro { get; set; }
        public sbyte SelCreaOrdenPedidoParametro { get; set; }
        public sbyte VerResumenOrdenPedidoParametro { get; set; }
        public sbyte VerPrecioTransferenciaParametro { get; set; }
        public sbyte SelCreaTransferenciaParametro { get; set; }
        public sbyte SelVendedorFacturaParamentro { get; set; }
        public sbyte VerPrecioTrabajoLaboratorioParametro { get; set; }
        public string VencimientoMaximoParametro { get; set; }
        public double MultaMinutoRetrazoParametro { get; set; }
        public int TiempoEsperaRetrazoParametro { get; set; }
        public int TiempoEsperaHoraExtraParametro { get; set; }
        public double EmpleadoIessparametro { get; set; }
        public double PatronoIessparametro { get; set; }
        public double MultaNoMarcadoParametro { get; set; }
        public string VerPrecioPactadoVentaParametro { get; set; }
        public double SecuenciaProductoParametro { get; set; }
        public string NumeroFacturaGrabarParametro { get; set; }
        public double Isdparametro { get; set; }
        public string ContabilizarFechaPagoParametro { get; set; }
        public int NumeroProductosFacturaParametro { get; set; }
        public int DiasSobregiroImportacionParametro { get; set; }
        public string CosteandoParametro { get; set; }
        public string ContabilizarFechaPagoClienteParametro { get; set; }
        public string ClienteDefectoFacturacionParametro { get; set; }
        public string FormaPagoFacturaDefectoParametro { get; set; }
        public string ResolucionContribuyenteEspecialParametro { get; set; }
        public string CuadreCajaParametro { get; set; }
        public double PorcentajeGastoImportacionParametro { get; set; }
        public string CuentaCompraInventarioParametro { get; set; }
        public string CantidadDecimalParametro { get; set; }
        public string DatosCotizacionProductoParametros { get; set; }
        public string DatosAdicionalesProductoParametros { get; set; }
        public string GuiasFacturas { get; set; }
        public string GenerarImpresionFacturaParametros { get; set; }
        public string GenerarSeguimientoFacturaParametros { get; set; }
        public string GenerarTelemarketingFacturaParametros { get; set; }
        public string EnviarMailFacturaParametros { get; set; }
        public string NumeroRetencionAutamaticoParametro { get; set; }
        public string ModuloMedicoParametro { get; set; }
        public string FormatoDocumentoParametro { get; set; }
        public string FormatoCondicionesParametro { get; set; }
        public string IpWiseParametro { get; set; }
        public double FondoReservaParametro { get; set; }
        public double Porcentajemaximomultaparametro { get; set; }
        public double ValorPagoDecimoCuartoParametro { get; set; }
        public string FechaPagoCostaXivparametro { get; set; }
        public string FechaPagoSierraXivparametro { get; set; }
        public string FechaPagoXiiiparametro { get; set; }
        public string ContabilizarEfectivoBancoParametro { get; set; }
        public double PorcentajeDescuentoAnual { get; set; }
        public int DiasCalculoAntesVencimiento { get; set; }
        public double PorcentajeDescuentoEmisionFactura { get; set; }
        public int DiasPagoFechaEmisionFacturacion { get; set; }
        public int PeriodoDiasRecalificacion { get; set; }
        public string FraseClienteCalificaVolumeE { get; set; }
        public string FraseClienteCalificaVolumeD { get; set; }
        public string FraseClienteCalificaVolumeC { get; set; }
        public string FraseClienteCalificaVolumeB { get; set; }
        public string FraseClienteCalificaVolumeA { get; set; }
        public string FraseClienteCalificaPagoE { get; set; }
        public string FraseClienteCalificaPagoD { get; set; }
        public string FraseClienteCalificaPagoC { get; set; }
        public string FraseClienteCalificaPagoB { get; set; }
        public string FraseClienteCalificaPagoA { get; set; }
        public int DiasBloqueoCambioCalificacionFacturacion { get; set; }
        public string ImprimirGuiaSinSerieParametro { get; set; }
        public string LogoEmpresaParametro { get; set; }
        public string IngresoNotaCreditoDirectaParametro { get; set; }
        public string DiaMaximoAnulacionFacturaParametro { get; set; }
        public string IngresoCompraDirectaParametro { get; set; }
        public string MaximoMesCalculoCupo { get; set; }
        public string FechaRegistroParametro { get; set; }
        public string CuentaContableAlInicioParametro { get; set; }
        public string ContabilizacionPagosDetalladoParametro { get; set; }
        public string DetalleContabilizacionParametro { get; set; }
        public string ParametroFromMailParametro { get; set; }
        public string ParametroHostMailParametro { get; set; }
        public string ParametroPasswordMailParametro { get; set; }
        public int ParametroPortMailParametro { get; set; }
        public string ParametroUserNameMailParametro { get; set; }
        public string ParametroUserNameMail1Parametro { get; set; }
        public string ParametroUserNameMail2Parametro { get; set; }
        public string ParametroUserNameMail3Parametro { get; set; }
        public string ParametroUserNameMail4Parametro { get; set; }
        public int NumeroMailsParametro { get; set; }
        public string CentroCostosParametro { get; set; }
        public string GenerarNumeroProduccionParametro { get; set; }
        public double PorcentajeSemaforoParametro { get; set; }
        public string EnviarMailPagosParametro { get; set; }
        public string AmbienteFacturacionElectronica { get; set; }
        public string GenerarNumeroNotaCreditoParametro { get; set; }
        public string NumeroDecimalesVentaParametro { get; set; }
        public string GastoIvaSeparadoParametro { get; set; }
        public string IngresarFechaDistintaRetencionparametro { get; set; }
        public string ObligarValorCalculadoParametro { get; set; }
        public double ValorVariacionRetencionParametro { get; set; }
        public string MailFacturaElectronicaParametro { get; set; }
        public string PuertoSalidaMailParametro { get; set; }
        public string ServidorSalidaMailParametro { get; set; }
        public string ClaveMailFacutacionElectronicaParametro { get; set; }
        public string MailNovedadesParametro { get; set; }
        public string ClaveMailNovedadesParametro { get; set; }
        public string MailRrhhparametro { get; set; }
        public string ClaveMailRrhhparametro { get; set; }
        public int NumeroRenovacionPendientesParametro { get; set; }
        public double ToleranciaRedondeoOrdenesParametro { get; set; }
        public string AutorizarOmitirDescuentoCupoClienteParametro { get; set; }
        public string ControlarGastosPresupuestoParametro { get; set; }
        public string ValidarMarcacionParametro { get; set; }
        public string CargarOrganigramaParametro { get; set; }
        public string ProductosProduccionDetalle { get; set; }
        public string AsientoDetalladoPagoProveedorParametro { get; set; }
        public string UbicacionFirmaElectronicaParametro { get; set; }
        public string ClaveFirmaElectronicaParametro { get; set; }
        public string ObligadoLlevarContabilidadParametro { get; set; }
        public string CorreoRetencionParametro { get; set; }
        public double PorcentajeDinardapParametro { get; set; }
        public string ValidarPuntoFacturaProveedorParametro { get; set; }
        public string VerificarBloqueoFormularioParametro { get; set; }
        public string VacioCuentaEfectivoParametro { get; set; }
        public double MaximoDiasFacturasXautorizar { get; set; }
        public string IsdliquidarImportacionParametro { get; set; }
        public double DiasGraciaVencimientoParametro { get; set; }
        public string UsuariosActivosParametro { get; set; }
        public string AnularImportacionConGastoParametro { get; set; }
        public string CodigoProductoFleteIvaParametro { get; set; }
        public string CreaDocPendienteDepositoCajaParametro { get; set; }
        public double ValorVariacionIvaParametro { get; set; }
        public string ModificarIvaGastoParametro { get; set; }
        public string MailComprasParametro { get; set; }
        public string ClaveMailComprasParametro { get; set; }
        public string CambiaVendedorAutomaticoOrdenes { get; set; }
        public string MailContabilidadParametro { get; set; }
        public string ClaveMailContabilidadParametro { get; set; }
        public string MailCarteraParametro { get; set; }
        public string ClaveMailCarteraParametro { get; set; }
        public string LectorBarraParametro { get; set; }
        public string CuentasCategorizadasEmpleadosParametros { get; set; }
        public string MensajeMailFacturaParametro { get; set; }
        public string EnviarMailRideParametro { get; set; }
        public string VerificarFirmaElectronicaParametro { get; set; }
        public string Textocartavacacionparametro { get; set; }
        public string EmpleadosJefeRrhhparametro { get; set; }
        public double IvaCompraParametro { get; set; }
        public string MaximoValorAtrasoParametro { get; set; }
        public string ProveedoresTipoGastoParametro { get; set; }
        public string VerificarNoAplicaClienteOrdenes { get; set; }
        public string VerificarNoAplicaClienteFactura { get; set; }
        public string VerificarNoAplicaProductoOrdenes { get; set; }
        public string VerificarNoAplicaProductoFactura { get; set; }
        public string IngresaComisionesParametro { get; set; }
        public double ValorDefectoCupoClienteParametro { get; set; }
        public double SueldoBasicoAnioAnteriorParametro { get; set; }
        public string CuentaContableNoAplica { get; set; }
        public string ContabilizarIvaSustentoParametro { get; set; }
        public int ParametroDescuentoAdicionalMaximo { get; set; }
        public int ParametroActivoPromociones { get; set; }
        public int NumeroDiasLiquidacionParametro { get; set; }
        public int MinutosTrabajoMesParametro { get; set; }
        public double PorcentajeIncrementoHoraExtraParametro { get; set; }
        public string FacturacionElecronicoParametro { get; set; }
        public int DiasAnticipacionSolicitudVacacionParametro { get; set; }
        public string CargarSeriesItemsFacturacionParametro { get; set; }
        public string NumeroResolucionContribuyenteParametro { get; set; }
        public string BotonActulizarPreciosProductoParametro { get; set; }
        public string ParqueaderoCarrosParametro { get; set; }
        public string RepresentanteParqueaderoCarrosParametro { get; set; }
        public double IceParametro { get; set; }
        public string CirepresentanteParqueaderoCarrosParametro { get; set; }
        public string SumarPagosCierreCajaParametro { get; set; }
        public string CargarHistorialClientesFactura { get; set; }
        public string AgregarDescripcionFacturaParametro { get; set; }
        public string AutorizarCupoFacturaParametro { get; set; }
        public string AutorizarPlazoFacturaParametro { get; set; }
        public string AutorizarDiasVencidosFacturaParametro { get; set; }
        public string AutorizarChequesProtestadosFacturaParametro { get; set; }
        public string PedirAutorizacionFacturaParametro { get; set; }
        public string VerificarNoAplicaIngresoClienteParametro { get; set; }
        public int NumeroCuotasMaximoParametro { get; set; }
        public string AutorizarPrecioFacturaParametro { get; set; }
        public string EquiposEmpleadosMovilParametros { get; set; }
        public string ContabilizaAnticipoCuentaContableProveedorParametro { get; set; }
        public string LigarFacturasDepositoTarjetaCredito { get; set; }
        public string ImprimirContratoEmpleadoParametro { get; set; }
        public double ValorRecargoProtestoParametro { get; set; }
        public string GeneraRecargoPagosParametro { get; set; }
        public double ValorRecargoDevolucionChequeParametro { get; set; }
        public int ServicioParametro { get; set; }
        public string SeleccionBodegaMovilParametros { get; set; }
        public double PorcentajeInteresXmoraParametro { get; set; }
        public string Parametroidapple { get; set; }
        public string ListasPreciosFacturacionParametro { get; set; }
        public int PermitirDarBajaItemsRecetaParametro { get; set; }
        public int GenerarDebitosBancariosParametro { get; set; }
        public string CargarXmldetalleCompraParametro { get; set; }
        public string PermitirAnularRetencionesCajaCerrada { get; set; }
        public int DiasVencimientoCreditosParametros { get; set; }
        public string ProcesoAnulacionFacturaParametro { get; set; }
        public string ParametroFactorProveedorImportacion { get; set; }
        public int ParametroLimiteBuscadoresProductos { get; set; }
        public string ParametroVerificarDatosChequesGrabarFactura { get; set; }
        public string ParametroVizualizacionDescuentoFactura { get; set; }
        public int InsertarDirectamenteClientesPlazosParametro { get; set; }
        public string SeguridadSslmailParametro { get; set; }
        public string VerificarValorAprobadoOrpparametro { get; set; }
        public int NotaCreditoDescuentoCostoParametro { get; set; }
        public string VerificarFacturaMismaEmpresaParametro { get; set; }
        public string UtilizarBdimpresionParametro { get; set; }
        public string EnviarMailOrpparametro { get; set; }
        public string FechaBloqueadaCobroClientesParametro { get; set; }
        public string AnticiposManejoCajaParametro { get; set; }
        public string ActivarCheckAnticipoPagosParametro { get; set; }
        public string ContabilizarSucursalPagosClientesParametro { get; set; }
        public string ContabilizarSucursalAnticiposClientesParametro { get; set; }
        public string RetencionFechaRegistroGastoProveedorParametro { get; set; }
        public string RetencionFechaRegistroCompraProveedorParametro { get; set; }
        public string RetencionFechaRegistroCruceCompraProveedorParametro { get; set; }
        public string CerrarMesSaltadoConciliacionParametro { get; set; }
        public string PagosProveedorCajaChicaBeneficiarioParametro { get; set; }
        public string IngresaFechaMovimientoBancosParametro { get; set; }
        public string ImpresionDetalladaManejoCajaParametro { get; set; }
        public string EsquemaOfflineFacturacionElectronicaParametro { get; set; }
        public double MesesTrabajadoEmpleadoAnticipoParametro { get; set; }
        public string AutorizarFacturasElectronicasModuloRestaurantParametro { get; set; }
        public string NotaRideFacturacionElectronica { get; set; }
        public string VisualizarDescuentosTotalesOrdenParametro { get; set; }
        public string UsarDescuentosTotalesOrdenParametro { get; set; }
        public string AutorizacionOrdenPorVendedorParametro { get; set; }
        public string PagosManejoCajaParametro { get; set; }
        public string DepositoDirectoChequeParametro { get; set; }
        public string ComprarServiciosParametro { get; set; }
        public string SegmentacionClientesParametro { get; set; }
        public string SolicitudOrdenGastoParametro { get; set; }
        public string ImpresoraEtiquetasParametro { get; set; }
        public string CodificacionPrecioVentaParametro { get; set; }
        public string PagoQuincenaCuentaEmpleadoParametro { get; set; }
        public string GeneraNumeroFacturaDeudaParametro { get; set; }
        public string ImprimirTirillaRideParametro { get; set; }
        public string UsarPlantillaCuentasContablesEmpleadoParametro { get; set; }
        public string OrdenConsignacionParametro { get; set; }
        public string UsuarioGestionRouterParametro { get; set; }
        public byte[] ClaveGestionRouterParametro { get; set; }
        public string AutorizacionFacturaPorVendedorParametro { get; set; }
        public string ImprimirProvisionesRolParametro { get; set; }
        public string ValidarAnulacionCompraParametro { get; set; }
        public int CantidadDecimalVentaParametro { get; set; }
        public string EmpresaServiciosMensualesParametro { get; set; }
        public string CargarSucursalSessionDetalleGastoParametro { get; set; }
        public int? NumeroDecimalesComprasParametro { get; set; }
        public int MaximoDiasGenerarGuiaFactuaParametro { get; set; }
        public string IngresarDetalleCargaGuiaFacturaParametro { get; set; }
        public int NumeroMaximoItemsTranferenciaInternaParametro { get; set; }
        public string ModificaCamposAutorizacionFechaProveedorParametro { get; set; }
        public string SecuenciaAutomaticaChequeParametro { get; set; }
        public string TasaArancelariaParametro { get; set; }
        public string UsarTablaIngresoBonosParametro { get; set; }
        public string ImprimirTotalDeudaReciboClienteParametro { get; set; }
        public string ListaPrecioDefectoCreacionClienteRapidaParametro { get; set; }
        public string SeleccionaImpresionRideFacturaParametro { get; set; }
        public string SeriesBilletes100Arqueo { get; set; }
        public string SeleccionarListaPreciosClienteFacturaParametro { get; set; }
        public string CalificacionArtesanalParametro { get; set; }
        public string VerificarDepositoCajaParametro { get; set; }
        public string CuentaAdicionaManejoChequeParametro { get; set; }
        public string InteresxMoraCobrosParametro { get; set; }
        public decimal PorcentajeInteresAnualCobrosParametro { get; set; }
        public string NotaRideRestaurantParametro { get; set; }
        public string FirmaRecibidoGuiaElectronicaParametro { get; set; }
        public string UsarCuentaTransitoriaDebitoParametro { get; set; }
        public string NumeracionContratoAgrupadoParametro { get; set; }
        public string ImprimirPrecioVentaEtiquetaProductoParametro { get; set; }
        public string ImprimirReferenciaEtiquetaProductoParametro { get; set; }
        public string ImprimirUbicacionEtiquetaProductoParametro { get; set; }
        public string PermitirGrabarDepositoTarjetaDescuadreParametro { get; set; }
        public string CalificacionClienteNuevoParametro { get; set; }
        public string ImprimirNombresImpresionFacturaParametro { get; set; }
        public string AplicaInteresFacturaParametro { get; set; }
        public string ReconexionAutomaticaPagoDeudaParametro { get; set; }
        public decimal CantidadCuotaPagoReconexionParametro { get; set; }
        public decimal ValorMaximoVentaConsumidorFinalParametro { get; set; }
        public string PermitirFacturarBajoCostoParametro { get; set; }
        public string ActivarVentaProductosParametro { get; set; }
        public string ContabilizarPrestamoIessparametro { get; set; }
        public string ImprimirObservacionCompletoFacturasParametro { get; set; }
        public string ImprimirCodigoBarraEtiquetaProductoParametro { get; set; }
        public string ImprimirNombreEmpresaEtiquetaProductoParametro { get; set; }
        public string FacturacionServiciosXclienteParametro { get; set; }
        public string GeneraNumeroFacturacionBloqueServiciosParametro { get; set; }
        public int NumeroUsuariosActivosParametro { get; set; }
        public string SeleccionarCuentaContableGatoParametro { get; set; }
        public string NumeracionMesualAsientoParametro { get; set; }
        public int PedirAutorizacionOrdenParametro { get; set; }
        public double PorcentajeDescuentoPrepagoFacturaParametro { get; set; }
        public string PlazosPorLineasClientesParametro { get; set; }
        public string EncuestarClienteParametro { get; set; }
        public string NotaImpresionFinalOrdenPedidoParametro { get; set; }
        public string NotaImpresionInicioOrdenPedidoParametro { get; set; }
        public string EmpresasGruposGastosParametro { get; set; }
        public string VisualizaValorConsignacionClienteParametro { get; set; }
        public string ControlaUnCambioMismoEstadoContratoParametro { get; set; }
        public string ValorAplicadoPromocionCorteParametro { get; set; }
        public string BloqueoCambioClienteContratoParametro { get; set; }
        public string BloqueoContratoCanceladoParametro { get; set; }
        public string ObligarSeleccionEquifaxAutorizacionContratoParametro { get; set; }
        public string SecuenciaNumeracionContratoXsucursalParametro { get; set; }
        public string BloqueoActualizacionNumContratoParametro { get; set; }
        public string AutorizaComprobanteEnCobroParametro { get; set; }
        public string NumeracionPuntoCajaFacturaServiciosParametro { get; set; }
        public string VerObservacionBuscadorFacturacClientesParametro { get; set; }
        public string EstadoActivoInterfazRemotaServiciosParametro { get; set; }
        public string FacturaServiciosMesesPosterioresParametro { get; set; }
        public double PorcentajeDescuentoPrepagoOrdenParametro { get; set; }
        public int ImprimirCuotasCreditoRideparametro { get; set; }
        public string ImprimeDireccionLocalContratoPagoParametro { get; set; }
        public string DepositarChequesInicialesPosfechadosManejoCheques { get; set; }
        public int NumeroMesHistorialVolumenComisionParametro { get; set; }
        public int NumeroMesHistorialMargenComisionParametro { get; set; }
        public decimal ValorIgualacionConciliacionParametro { get; set; }
        public string ArrastarDepositosTransitoVariosMesesParametro { get; set; }
        public string ObligarSeleccionPromocionIngresoContratoParametro { get; set; }
        public int ModificarPrecioFacturaParametro { get; set; }
        public int ControlarInventarioFacturaParametro { get; set; }
        public string CierreCajaSinArqueoParametro { get; set; }
        public int ImprimirFormaPagoDigitadoVehiculosParametro { get; set; }
        public string ImprimirLineaRideDetalleParametro { get; set; }
        public int NumeroCaracterDescripcionRideDetalleParametro { get; set; }
        public string ProcesoAutorizacionSolicitudNcparametro { get; set; }
        public string FuenteRideFacturaParametro { get; set; }
        public double TamanoFuenteRideFacturaParametro { get; set; }
        public int ImprimirNombreComercialFacturaTirillaParametro { get; set; }
        public int ImpresionDirectaFacturaParametro { get; set; }
        public int RefrescarLuegoDeImprimirFacturaParametro { get; set; }
        public string ManejoPvfcompraParametro { get; set; }
        public string GenererarRecibirCompraParametro { get; set; }
        public string NotaEstadoCuentaClienteParametro { get; set; }
        public string IngresaObservacionCarteraClientesParametro { get; set; }
        public DateTime FechaCargaInformacionSistemaParametro { get; set; }
        public int ControlViajesParametro { get; set; }
        public string UnirPrefacturasEnPagoParametro { get; set; }
        public string GenerarPagoDesdeContratoServicioParametro { get; set; }
        public string FacturacionActivacionServicioParametro { get; set; }
        public string ProcesoIngresarValorTarjetaCreditodeCajaParametro { get; set; }
        public string GestionaContratoPorServiciosParametro { get; set; }
        public string CalcularImpuestoRentaEmpleadoParametro { get; set; }
        public double NumeroVecesMaximoDeducibleParametro { get; set; }
        public string AutorizarHorasExtrasParametro { get; set; }
        public string ImprimirOrdenInstalacionContratoParametro { get; set; }
        public string PermitirActualizarFechaVentaContratoParametro { get; set; }
        public string ProcesoVentaActivosParametro { get; set; }
        public string ProcesoVentaReembolsoParametro { get; set; }
        public string AutorizarFacturasElectronicasModuloFacturacionParametro { get; set; }
        public string VisualizarCarteraDeudaMesActualParametro { get; set; }
        public string GrabarBitacoraRepCarteraXestadoParametro { get; set; }
        public string ImprimirSinCabeceraRideParametro { get; set; }
        public string CreacionRapidaProductosParametro { get; set; }
        public string ImprimirImagenServicioTecnicoParametro { get; set; }
        public double PorcentajeImagenServicioTecnicoParametro { get; set; }
        public string ModificaFechaServicioTecnicoParametro { get; set; }
        public string DecimalesLibroMayorParametro { get; set; }
        public string OrpformaCotizacionParametro { get; set; }
        public int ArquearCajaSinTotalesParametro { get; set; }
        public int NumDiasDescuentoReconexionGeneracionNcvparametro { get; set; }
        public string ObligarCobroClientesFacturaMasAntigua { get; set; }
        public int DiasAvisoConsignacionParametro { get; set; }
        public int DiasBloqueoConsignacionParametro { get; set; }
        public int ImprimirDetalleDobleLineaParametro { get; set; }
        public int ImpresionDirectaCierreCajaParametro { get; set; }
        public string FiltroPromedioDeudaCarteraSinDecimalesParametro { get; set; }
        public string FiltroPlacaServicioTecnicoParametro { get; set; }
        public string PermitirTranferenciaServiciosParametro { get; set; }
        public string VariosCodigosCompraParametro { get; set; }
        public string ImprimirRideNormalCreditoParametro { get; set; }
        public string ControlarCupoClienteParametro { get; set; }
        public decimal PorcentajeDescontarTarjetaCreditoVentaParametro { get; set; }
        public string VerificarDescuentoRestarTarjetaCreditoVentaParametro { get; set; }
        public string OrdenCompraReporteRotacionParametro { get; set; }
        public string PalabraCodificacionEtiquetaVentaParametro { get; set; }
        public int NumeroLetrasCalificacionParametro { get; set; }
        public int FacturaUsuarioAperturaCajaParametro { get; set; }
        public string BodegaDefectoCotizacionParametro { get; set; }
        public double AnchoEtiquetaVentaParametro { get; set; }
        public string IngresoComisionesSinGrabarParametro { get; set; }
        public string ComisionCalculadaTablaParametro { get; set; }
        public string ImprimirNombreComercialEmpresaEtiquetaProductosParametro { get; set; }
        public string ImprimirNombreEmpresaEtiquetaProductosParametro { get; set; }
        public string ContabilizarOtraBaseRolParametro { get; set; }
        public string TipoAsientoRolOtraBaseParametro { get; set; }
        public string GenerarTxtbancarioParametro { get; set; }
        public int PermitirModificarOrdenPedidoParametro { get; set; }
        public string GestionaCientesEquifaxParametro { get; set; }
        public string ServiciosManejaComboContratoParametro { get; set; }
        public double AltoCodigoBarraEtiquetasProductoParametro { get; set; }
        public string DepositoLotesCajaParametro { get; set; }
        public string Generarasientosdepreciacioncomprasactivosparametro { get; set; }
        public int GeneraProductoCotizacionParametro { get; set; }
        public int FacturarPromocionConsumidorFinalParametro { get; set; }
        public int ExistenciaAdminitracionProductosParametro { get; set; }
        public double CantidadOrdenCompraParametro { get; set; }
        public int MesesAntiguedadMaximaFacturaReconexionPagoParametro { get; set; }
        public string PonderarIceDauImportacionParametro { get; set; }
        public int ServicioRecargasElectronicasParametro { get; set; }
        public int UsarLectorBarrasNativoFacturaParametro { get; set; }
        public string CodigoDocumentoTxtbancoParametro { get; set; }
        public string BloqueaAnticipoCobrosParametro { get; set; }
        public string ImprimirNombresImpresionGuiaParametro { get; set; }
        public string ValorAbsolutoListaPrecioParametro { get; set; }
        public string CargarBodegasDetalleFacturaNotaCreditoVentaParametro { get; set; }
        public int VerificarPlazosPorLineaFacturaParametro { get; set; }
        public int VerificarPlazosPorLineaOrdenParametro { get; set; }
        public int VerificarPlazosProductoXlineaFacturaParametro { get; set; }
        public int VerificarPlazosProductoXlineaOrdenParametro { get; set; }
        public string GenerarTurnoFacturaParametro { get; set; }
        public string IngresarPacienteFacturaParametro { get; set; }
        public int ParametroLimiteBuscadores { get; set; }
        public string PeriodoUbgrupoEconomico { get; set; }
        public string TipoGastoSolicitarCotizacionParamentro { get; set; }
        public string FuenteRideGuiaParametro { get; set; }
        public double TamanoFuenteRideGuiaParametro { get; set; }
        public string FuenteRideNotaCreditoVentaParametro { get; set; }
        public double TamanoFuenteRideNotaCreditoVentaParametro { get; set; }
        public int IngresaNumeroOrdenCompraFacturaParametro { get; set; }
        public string UsuarioIngresaVacacionesParametro { get; set; }
        public string LigarChequesPuntoFactura { get; set; }
        public string ModuloImportacionesParametro { get; set; }
        public string SolicitaNumeroReciboCobroParametro { get; set; }
        public string ModuloBuffersParametro { get; set; }
        public string FuenteRideRetencionParametro { get; set; }
        public decimal TamanoFuenteRideRetencionParametro { get; set; }
        public int BuscarSustitutosPorDescripcionAdicionalParametro { get; set; }
        public int AmbienteRecargasElectronicasParametro { get; set; }
        public int SeleccionaProveedorTranferenciaInternaParametro { get; set; }
        public int OrdenarXexistenciaBuscadorProductoParametro { get; set; }
        public int OmitirEmpleadosConAvisosIessSalidaFacturaParametro { get; set; }
        public int PermitirModificarCotizacionesDeOtroUsuario { get; set; }
        public int SolicitarClaveProduccionVariacionCostoMayorParametro { get; set; }
        public string ClaveProduccionVariacionCostoMayorParametro { get; set; }
        public string ConvertirUnidadesCajaCompraParametro { get; set; }
        public int FiltrarVendedoresPorRolPagosParametro { get; set; }
        public string ProductoGastosOrdenServicioTecnicoParametro { get; set; }
        public string IpEmpresaPrincipalParametro { get; set; }
        public int PuertoEmpresaPrincipalParametro { get; set; }
        public decimal PorcentajeToleranciaVariacionCostoParametro { get; set; }
        public int ManejaMotivosCategoriasCallCenterParametro { get; set; }
        public int OcultarRucPantallaPagosProveedoresParametro { get; set; }
        public int OcultarEmpresaPantallaPagosProveedoresParametro { get; set; }
        public int OcultarSucursalPantallaPagosProveedoresParametro { get; set; }
        public int LiquidacionCompraElectronicaParametro { get; set; }
        public int VisualizarExistenciaTodasBodegasFacturaParametro { get; set; }
        public string FuenteImpresionSolicitudVacacionesParametro { get; set; }
        public decimal TamanoFuenteImpresionSolicitudVacacionesParametro { get; set; }
        public int OcultarObservacionCobroClientesParametro { get; set; }
        public int OcultarMesConsumoCobroClientesParametro { get; set; }
        public int FacturarVariasOrdenesServicioTecnicoJuntasParametro { get; set; }
        public int UsarFirmaElectronicaEncriptadaParametro { get; set; }
        public decimal TamanoFuenteNombreProveedorImpresionCheque { get; set; }
        public string FuenteRideLiquidacionCompraParametro { get; set; }
        public int MostrarAnticiposCarteraParametro { get; set; }
        public int AgregarProductoDescuentoNotaCreditoCompras { get; set; }
        public string ProductoDescuentoNotaCreditoCompras { get; set; }
        public string ProductoIvaDescuentoNotaCreditoCompras { get; set; }
        public int ContabilizarDetalleSucursalGastoParametro { get; set; }
        public int ImprimirCodigoVentaEtiquetaProductoParametro { get; set; }
        public int ImprimirBaseLineEtiquetaProductoParametro { get; set; }
        public int AnioInicioSistema { get; set; }
        public int MesInicioSistema { get; set; }
        public int ContabilizarVacacionesParametro { get; set; }
        public decimal MontoDescuadreGeneraAnticipoParametro { get; set; }
        public string TamanoFuenteRideLiquidacionCompraParametro { get; set; }
        public int OcultarLocaliacionPagosClientesParametros { get; set; }
        public string CuentaDefectoSaldarAnctipoParametros { get; set; }
        public int EnviarMailBitacoraFacturaParametro { get; set; }
        public int CentroCostoFacturaParametro { get; set; }
        public string PagoSriDefectoParametro { get; set; }
        public int VerificaNumTransferenciaRegistradaParametro { get; set; }
        public int HorasExtrasFormatoEnteroParametro { get; set; }
        public int ImpresionHorizontalChequeParametro { get; set; }
        public double PosicionInicialXimpresionChequeParametro { get; set; }
        public double PosicionInicialYimpresionChequeParametro { get; set; }
        public int HorasExtrasJornadaNocturnaParametro { get; set; }
        public int ClienteDebeAprobarCotizacionParametro { get; set; }
        public int VerificarPendientesLiquidacionProduccionParametro { get; set; }
        public int ImprimirCodigoBarrasPiePaginaRideFacturaParametro { get; set; }
        public int LigarVariasOrdenesCompraParametro { get; set; }
        public int ObligarLigarOrdenesCompraParametro { get; set; }
        public string VendedorDefectoProtestoDevolucionChpCarIniParametro { get; set; }
        public int GenerarDespachosFacturaParametro { get; set; }
        public int ProcesoRecosteoIsdparametro { get; set; }
        public int ProcesoImpresionSobreVentaParametro { get; set; }
        public double TamanoFuenteNombreImpresionSobreVentaParametro { get; set; }
        public double PosicionInicialXimpresionSobreVentaParametro { get; set; }
        public double PosicionInicialYimpresionSobreVentaParametro { get; set; }
        public int PorRecibirConsignacionMovilParametro { get; set; }
        public int SistemaMovilParametro { get; set; }
        public int ImpresionDirectaNotaCreditoParametro { get; set; }
        public int ImpresionDirectaTransferenciaItemsParametro { get; set; }
        public int CtrlFinDeSemanaVacacionesParametro { get; set; }
        public int CrearItemsComprasParametro { get; set; }
        public int ImprimirSaldoChequesPosfechadosParametro { get; set; }
        public int AgregarMarcaReporteCarteraClientesParametro { get; set; }
        public int ModuloEcommerceParametro { get; set; }
        public decimal PorcentajeInventarioDisponibleEcommerceParametro { get; set; }
        public int CortesBloqueReduceVelocidadParametro { get; set; }
        public string ProductoTransporteEcommerceParametro { get; set; }
        public int CargarExcelOrpparametro { get; set; }
        public int FiltrarSucursalPuntosFacturaServicioTecnicoParametro { get; set; }
        public string UrlpublicaSistema { get; set; }
        public int PermitirCargarProductosNotaCreditoDescuentoParametro { get; set; }
        public int SustitutosRecetasParametro { get; set; }
        public int ImprimirVendedorFacturaParametro { get; set; }
        public int ImprimirDescuentoFacturaParametro { get; set; }
        public int ImprimirFormaPagoFacturaParametro { get; set; }
        public int ImprimirEnvioRetencionFacturaParametro { get; set; }
        public int ImprimirFormaPagoSriFacturaParametro { get; set; }
        public int ImprimirValidezTributariaFacturaParametro { get; set; }
        public int ProcesoReemplazarCompraDetalleParametro { get; set; }
        public int GenerarExcelReembolsoGastosParametro { get; set; }
        public int GuiaTransporteApiParametro { get; set; }
        public int ActivarDescuentoProductoVentaEnCompraParametro { get; set; }
        public int CompresionVelocidadServicioParametro { get; set; }
        public int AmbienteSincronizacionDatosApiEcommerce { get; set; }
        public int PermitirGenerarAnticipoNccompraParametro { get; set; }
        public int EnviarMailOrdenCompraPerfilAutorizaParametro { get; set; }
        public string ApiSincronizarEcommerceParametro { get; set; }
        public int VerSucursalIngresoOrdenServicioTecnico { get; set; }
        public int ProcesoPrecioMarcadoParametro { get; set; }
        public int ImprimirRecomendacionesInformeServicioTecnicoParametro { get; set; }
        public int ImprimirTerminosGarantiaInformeServicioTecnicoParametro { get; set; }
        public int IngresaDatosArcsaParametro { get; set; }
        public string TransportistaDefectoGuiasRemisionParametro { get; set; }
        public string PlacaDefectoGuiasRemisionParametro { get; set; }
        public string VendedorDefectoCargarClientesCorporativosParametro { get; set; }
        public int CargarExcelPromocionesParametro { get; set; }
        public int ImprimirFirmaClienteInformeServicioTecnicoParametro { get; set; }
        public int ObligaIngresaNumeroOrdenCompraFacturaParametro { get; set; }
        public int EmpleadoSinRolReporteCobros { get; set; }
        public int AgregarDetalleChequesReporteCarteraParametro { get; set; }
        public int RegimendeMicroempresasParametro { get; set; }
        public int AgenteRetencionParametro { get; set; }
        public int CargarExcelCrearOrdenesImportacioncesParametro { get; set; }
        public string ResolucionAgenteRetencionParametro { get; set; }
        public int PoderOmitirFacturasParaComisionesParametro { get; set; }
        public int CerrarCajaMismoUsuarioParametro { get; set; }
        public int CiudadReportesMatrizParametro { get; set; }
        public double LargoLogoRideParametro { get; set; }
        public double AnchoLogoRideParametro { get; set; }
        public string AlineacionHorizontalLogoRideParametro { get; set; }
        public string AlineacionVerticalLogoRideParametro { get; set; }
        public int CantidadMaximaHilosConcurrentesParametro { get; set; }
        public int ModificarValoresOrpaprobadaParametro { get; set; }
        public int ManejaTempariosServicioTecnicoParametro { get; set; }
        public int ImprimirDatosLocalizacionDestinoGuiaRideParametro { get; set; }
        public double ValorIsdparametro { get; set; }
        public int PagosClienteGeneraAnticipoParametro { get; set; }
        public int CargarExcelComisionesParametro { get; set; }
        public int ImpresionDescuentoTotalOrdenPedidoParametro { get; set; }
        public int ImprimirLeyendaAhorroTotalPrecioMarcadoParametro { get; set; }
        public string TextoLeyendaAhorroTotalPrecioMarcadoParametro { get; set; }
        public int ProcesoCargarExcelPrestamosIessParametro { get; set; }
        public string TipoAjusteTomaInventarioParametro { get; set; }
        public int ProcesoFacturacionCuponesParametro { get; set; }
        public double TamanioFuenteImpresionOrdenServicioTecnicoParametro { get; set; }
        public double TamanioFuenteImpresionInformeServicioTecnicoParametro { get; set; }
        public int HabilitarSecuenciaCobroMovilParametros { get; set; }
        public int AgregarMesComisionEmpleadoParametro { get; set; }
        public int ValidarSubtotalesNccomprasParametro { get; set; }
        public int ProcesoProgramacionPagosProveedoresParametro { get; set; }
        public int VizualizarEnCarteraNumeroChequeProtestadoParametro { get; set; }
        public int FiltrarXfechaCarteraClienteParametro { get; set; }
        public int RealizaDeclaracionSemestralParametro { get; set; }
        public int TieneCargaInicialChequesParametro { get; set; }
        public string ProductoDefectoMemoReferenciaImportacionParametro { get; set; }
        public int ModuloRefenciasImportacionParametro { get; set; }
        public double TamanioFuenteImpresionMemoParametro { get; set; }
        public int ImprimirObservacionCompletaPagosParametro { get; set; }
        public int OmitirContratosReporteCarteraClientesParametro { get; set; }
        public double TamanioFuenteComprobantePagoProveedoresParametro { get; set; }
        public int CargarFobSinFleteVerImportacionesParametros { get; set; }
        public int ActivarTotalesClienteCarteraClienteParametro { get; set; }
        public int VisualizarClienteReporteProtestosParametro { get; set; }
        public int VisualizarNumChequeReporteProtestosParametro { get; set; }
        public int ImpresionDescuentoSobrePvpordenPedidoParametro { get; set; }
        public int ActualizarValorCobroEnUnionPagoParametro { get; set; }
        public int PermitirVentaCreditoConsumidorFinalParametro { get; set; }
        public double AltoCodigoBarraRideFacturaParametro { get; set; }
        public int VizualizarEnPagosClienteNumeroChequeProtestadoParametro { get; set; }
        public int ImpresionDirectaPagoParametro { get; set; }
        public string UrlBaseRecursosImpresionParametro { get; set; }
        public int PermitirIngresoNumeroFacturaGastoReocParametro { get; set; }
        public int NumeracionSecuencialContratoParametro { get; set; }
        public int VisualizacionReportesVendedor { get; set; }
        public int ManejaDiaCorteContratoParametro { get; set; }
        public int PermitirActualizarVendedorContratoParametro { get; set; }
        public string CategoriaDocumentoLlamadaCallCenterParametro { get; set; }
        public int ConcatenarCodigoVentaImpresionDirectaParametro { get; set; }
        public int VerUtilidadFacturaSimpleParametro { get; set; }
        public string IdEmpresaXadisParametro { get; set; }
        public int WsxadisParametro { get; set; }
        public int ActivarListaPreciosClienteFacturaSimpreParametro { get; set; }
        public int LigarMaterialesOrdenServicioTecnicoParametro { get; set; }
        public int CargarVariosDetallesComprasNotaCreditoCompras { get; set; }

        public virtual Categoriastiposdocumentosinstalaciones CategoriaDocumentoLlamadaCallCenterParametroNavigation { get; set; }
        public virtual Tiposajustes TipoAjusteTomaInventarioParametroNavigation { get; set; }
    }
}
